# Numpy arrays and linear algebra 
As you've no doubt noticed, a lot of the material in this class will make use of linear algebra.  Matrix and vector multiplication (a la the dot product) are found in numerous places and you will undoubtebly use/see the `@` operator more than most any other.

2-dimensional numpy arrays behave pretty much like we would expect from matrices, but 1-dimensional numpy arrays (i.e. vectors) can be a funny thing.  They look like vectors, they act kind of like vectors, but they aren't vectors in the mathematical sense of the word.  Let me explain.

## Linear algebra and dot products

In math, a vector $\mathbf{x} \in \mathbb{R}^n$ is usually understood to be a *column vector*.  That is, if I were to write out $\mathbf{x}$ then it would look like

$$ \mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix} $$

When we write $\mathbf{x}^T$ that makes $\mathbf{x}$ a *row vector*.  So if I were to write out $\mathbf{x}^T$ it would look like

$$ \mathbf{x}^T = \begin{bmatrix} x_1 \,, x_2 \,, \cdots \,, x_n \end{bmatrix} $$

When I want to compute a dot product between two vectors $\mathbf{x}$ and $\mathbf{y}$ I write

$$ \mathbf{y}^T \mathbf{x} $$

Which means that this is the product between a *row vector* and a *column vector*. 


## One- and two dimensional arrays in numpy
Intuitively, we expect that Numpy behaves the same way. The confusion arises because vectors can be represented as 1-d or 2-d arrays. 

In [37]:
import numpy as np

# This is a one-dimensional numpy array  
x = np.array([1,2,3])
y = np.array([4,5,6])

print('x looks like:')
print(x)
print(y)

x.shape

x looks like:
[1 2 3]
[4 5 6]


(3,)

In [38]:
# We can also store these column vectors in two-dimensional numpy array  
X = np.array([[1,2,3]]).T
Y = np.array([[4,5,6]]).T

print('X looks like:')
print(X)
print(Y)

X.shape

X looks like:
[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


(3, 1)

## Dot products in numpy 
The dot-product between two 2d-arrays behaves as we would expect: 

In [39]:
# row vector by column vector results in a scalar 
print(X.T@Y)

[[32]]


Note that the result is still technically a 2-d array.  

In [40]:
# If the sizes of the arrays do not align, I am getting an error message 
X@Y

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

 But take a look at what happens when I compute the dot product between two arrays using `@`.

In [41]:
# I shouldn't be able to do either of these operations with vectors
# because they don't have the right shape
print(x@y)
print(y@x)
# But as you can see, I can:

32
32


This isn't allowed to happen in linear algebra.  If `x` and `y` are "vectors", then numpy is allowing me to take the product of two column vectors without transposing one of them.  The answer is right, the dot product is 32, but 1-d numpy arrays do not behave like vectors.  

Indeed, the transpose operator leaves a 1-d array unchanged

In [42]:
print(x)
print(x.T)

[1 2 3]
[1 2 3]


A useful function to transform 1-d arrays into 2-d arrays is the function `reshape`. We can transform or data into  `(n,1)` shaped arrays using `x.reshape(-1,1)`.  When you pass `-1` to reshape, you're telling numpy to infer the shape in that dimension.  So if I had an array, `z`, of 3 elements and I called `z.reshape(-1,1)`.  This will reshape the array to be a `(3,1)` array.  We didn't have to tell numpy the size for the first dimension, numpy inferred it from the size of the array.

Watch what happens when I now try to take the dot product between these two arrays.

In [43]:
X = x.reshape(-1,1)
Y = y.reshape(-1,1)

print('X looks like:')
print(X)
print('Y looks like: ')
print(Y)

X looks like:
[[1]
 [2]
 [3]]
Y looks like: 
[[4]
 [5]
 [6]]


Now, these column vectors will behave like I would expect from vectors in linear algebra: 

In [44]:
(X.T@Y)

array([[32]])

Possibly confusingly, numpy also defines a dot product between a 2-d array and a 1-d array

In [45]:
X.T@y

array([32])

Note that the result now is a 1d-array

For Assignment 1, you need to be clearly aware of whether you are using 1-d array or 2-d arrays. It will take some time to develop the right intuitions here. 
For starters it is useful to work consistently with 2-d arrays and ensure that the shapes are appropriate and conducive to multiplication, and that they respect the rules for taking the dot product.  If you are having shape issues, or if you are getting `ValueErrors` mentioning `matmul` (`@` is an alias for `np.matmul`) then I highly suspect the issue will be rectified by considering the topics discussed here.